---
deployment:
  tasks:
    - export DEPLOYPATH="/home/seanljvy/public_html/"

    # Copy individual files
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp general.css $DEPLOYPATH
    - /bin/cp general.js $DEPLOYPATH
    - /bin/cp icon.jpg $DEPLOYPATH

    # Copy entire directories
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
