---
deployment:
  tasks:
    - export DEPLOYPATH="/home/seanljvy/repositories/seants.me"

    # Copy individual files
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp general.css $DEPLOYPATH
    - /bin/cp general.js $DEPLOYPATH

    # Copy entire directories
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH

    # (Optional) If you also have index.html or other top-level HTML files,
    # you can copy them similarly:
    # - /bin/cp index.html $DEPLOYPATH
